### ISSUE TITLE
Adjustable width between panes

### ISSUE THREAD

**Issue by Rye42** [vran-dev/obsidian-composer#25]
感谢开发者制作的主题，很好看！但是有些地方的空间有点利用不完全，对小屏不太友好。
请问如何更改图中紫色区域的宽度，我尝试更改 css 文件，但是没有找到这个变量。

![Image](https://github.com/user-attachments/assets/e35c2b40-f403-4e8d-93e2-b31aff1e28db)  

## 目前的窗口样式(我用红框标出了不易察觉的几处)： 

![Image](https://github.com/user-attachments/assets/bf5d381c-681b-4d73-b2bf-f2a687f41c5f)  

## 希望的样式： 

![Image](https://github.com/user-attachments/assets/9ebe925a-fdd3-4047-afc3-9a50d6372c01)  

这里运用的主题是 Anuppuccin。同样采用了卡片式布局，中间分隔的宽度和 resize-handle 宽度相仿。
如果可以的话，希望开发者能将宽度调整设置加入 style settings 中。

**Comment by vran-dev** [comment]
将下面的代码添加到 css snippets 中，调整一下 `16px` 数值即可

```css
body:not(.is-mobile) .workspace-split.mod-vertical,
body:not(.is-mobile) .workspace-split.mod-horizontal {
	gap: 16px;
}
```
