### ISSUE TITLE
FR：Support changing outline styles through style settings

### ISSUE THREAD

**Issue by vran-dev** [vran-dev/obsidian-composer#7]
change lines 1603

```css
.workspace-leaf-content[data-type="outline"] .tree-item-children {
	border-inline-start: none;
}
```

to 

```css
.workspace-leaf-content[data-type="outline"] .tree-item-children {
    border-inline-start: var(--nav-indentation-guide-width) solid var(--nav-indentation-guide-color);
}
```

and set `--nav-indentation-guide-width` to  0px default,   user can change width through style settings plugin

```css
body {
...
 /*others*/
  --nav-indentation-guide-width: 0px;
}
```
